# Enlista los productos que necesitamos comprar pero no son parte de alguna receta en particular
# Cantidad no especificada es igual a 1
pan:
  cantidad: 1
  unidad: "barra"
  seccion: "abarrotes"
aguacate:
  cantidad: 1
  unidad: bolsa
  seccion: "verduras"
walmart_jabon_ropa:
  cantidad: 3
  unidad: "botella"
  seccion: "pasillo"
suavitel:
  cantidad: 1
  unidad: "botella"
  seccion: "pasillo"
